namespace MeasurementConverter.Length.Enums
{
    public enum MetricLengthUnit
    {
        RONNAMETER,
        YOTTAMETER,
        ZETTAMETER,
        EXAMETER,
        PETAMETER,
        TERAMETER,
        GIGAMETER,
        MEGAMETER,
        KILOMETER,
        HECTOMETER,
        DECAMETER,
        METER,
        DECIMETER,
        CENTIMETER,
        MILIMETER,
        MICROMETER,
        NANOMETER,
        PICOMETER,
        FEMTOMETER,
        ATTOMETER,
        ZEPTOMETER,
        YOCTOMETER,
        RONTOMETER,
        FOOT,
    }
}